
DROP TABLE ADMINSMESSAGE;
DROP TABLE TOURISTMESSAGE;
DROP TABLE REVIEW;
DROP TABLE GUIDEMESSAGE;
DROP TABLE ISSUE;
DROP TABLE BOOKING;
DROP TABLE SESSION;
DROP TABLE TOUR;
DROP TABLE USERS; 
DROP TABLE ADMINS;
