
version: "3.2"

services:

  sql-server-db:
    container_name: Homer 
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"

